name: Build and Publish C# Project

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache .NET dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Restore dependencies
        run: dotnet restore SharpTimer.csproj

      - name: Build the project
        run: dotnet build --configuration Release SharpTimer.csproj

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish SharpTimer.csproj

      - name: Set version tag and zip file name
        id: version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            TAG="Prerelease $VERSION"
          else
            TAG="$VERSION"
          fi
          ZIP_NAME="SharpTimer_${VERSION}.zip"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Zip published files
        run: |
          # Create necessary directories
          mkdir -p publish/addons/counterstrikesharp/plugins/SharpTimer/
          
          # Move files and directories inside ./publish to the target directory (without causing circular references)
          find ./publish -mindepth 1 -maxdepth 1 ! -name 'cfg' ! -name 'lang' -exec mv {} publish/addons/counterstrikesharp/plugins/SharpTimer/ \;
          
          # Zip all directories inside ./publish (but not the ./publish directory itself)
          find ./publish -mindepth 1 -maxdepth 1 -type d -exec zip -r ${{ env.ZIP_NAME }} {} +

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.16.0
        with:
          name: ${{ env.TAG }}
          artifacts: ${{ env.ZIP_NAME }}
          prerelease: ${{ contains(github.ref, 'dev') }}
          tag: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
